### ISSUE TITLE
Missing python-gobject dependency on Arch Linux

### ISSUE THREAD

**Issue by IpsissimusMarr** [ricardomv/snapper-gui#11]
After installing all listed dependencies (minus snapper-git) and installing, snapp produces the following error:
```
$ snapper-gui
Traceback (most recent call last):
  File "/usr/bin/snapper-gui", line 9, in <module>
    load_entry_point('snappergui==0.1', 'gui_scripts', 'snapper-gui')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/snappergui-0.1-py3.5.egg/snappergui/application.py", line 2, in <module>
ImportError: No module named 'gi'
```

But installing python-gobject takes care of the issue:
```
pacman -S python-gobject
```

May want to include it in your Arch dependency list.

**Comment by ricardomv** [comment]
Thanks i will update it.
