### ISSUE TITLE
lost one dependency for ubuntu xenial

### ISSUE THREAD

**Issue by sbr9150** [ricardomv/snapper-gui#20]
I use ubuntu mate xenial. I cannot get gui working without gir1.2-gtksource-3.0. Please include this to dependency for ubuntu. Thank you.

**Comment by tinstep** [comment]
I can confirm this bug. I followed the instruction in the readme, and got the following.

`sudo snapper-gui 
Traceback (most recent call last):
  File "/usr/local/bin/snapper-gui", line 9, in <module>
    load_entry_point('snappergui==0.1', 'gui_scripts', 'snapper-gui')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/snappergui/__init__.py", line 5, in <module>
    gi.require_version("GtkSource", "3.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available`

once I did a 
`sudo apt install gir1.2-gtksource-3.0`
it now runs fine.

**Comment by ricardomv** [comment]
Fixed, thanks.
