### ISSUE TITLE
When creating snapshot: dbus.exceptions.DBusException: error.unknown_config: org.freedesktop.DBus.Error.Failed

### ISSUE THREAD

**Issue by jbrepogmailcom** [ricardomv/snapper-gui#38]
This error I get when I try to create btrfs snapshot.

**Comment by PotcFdk** [comment]
First reported [here](https://github.com/ricardomv/snapper-gui/issues/31#issuecomment-407633128)

**Comment by ricardomv** [comment]
You need to provide more information on the issue. Are you able to create snapshots using the command line interface?

**Comment by AlexanderGabriel** [comment]
I installed a new Debian 11.4 on a VM and tried snapper-gui.
Had the same error when trying to make a snapshot with snapper-gui. no matter if i uesed the debian package or the latest git, i got the folllowing error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/snappergui/mainWindow.py", line 94, in on_create_snapshot
    newSnapshot = snapper.CreateSingleSnapshot(dialog.config,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: error.unknown_config: org.freedesktop.DBus.Error.Failed


I was able to make a snapshot with btrfs command:
root@btrfs:~# btrfs subvolume snapshot / /test
Create a snapshot of '/' in '//test'

So i tried to use snapper and there was no config at snapper list-config. After i created one, it worked.

Maybe you can catch this error or disable the snapshot function and tell the user to first create a config before opening the create snapshot dialog.

**Comment by auspex** [comment]
It's easily reproducible on Ubuntu 24.04. If run as a user, and you don't have a config, it can't create one. What permissions does one need to access DBus?  Running as root, it's all good, but I want to be able to allow users to schedule their own snapshots on their own subvolumes.
