### ISSUE TITLE
dbus.exceptions.DBusException when trying to find file difference

### ISSUE THREAD

**Issue by MasterCATZ** [ricardomv/snapper-gui#39]
Ubuntu 18.04

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/snappergui/changesWindow.py", line 138, in on_idle_init_paths_tree
    snapper.CreateComparison(self.config,self.snapshot_begin,self.snapshot_end)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

when I  first installed snapper it all seemed to work 1 week later when I needed it .. it started doing this 

still unsure what happened some time after snapshot 10 a folder was wiped 
issue being folders contents spanned across 20 disks would be nice using a gui instead of doing 

snapper -c SRD9NA1B8 -v undochange 1..161 /mnt/SnapRaidArray/SRD9NA1B8/ ...
for each and every file / mounted disk 

possibly a python related issue ? 

![Screenshot from 2019-12-02 08-24-14](https://user-images.githubusercontent.com/1857824/69921412-30f65780-14dd-11ea-97d8-f44d07c5a9e8.png)

**Comment by philipp-classen** [comment]
Comparing two snapshots can take a while. If it exceeds the default timeout of dbus (25 seconds in my case), the call times out. That is why the difference window shows no changes.

This is where the call takes place (it proxies to dbus):
https://github.com/ricardomv/snapper-gui/blob/f0c67abe0e10cc9e2ebed400cf80ecdf763fb1d1/snappergui/changesWindow.py#L142

This is the exception
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/snappergui/changesWindow.py", line 142, in on_idle_init_paths_tree
    snapper.CreateComparison(self.config, self.snapshot_begin, self.snapshot_end)
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

Unfortunately, I'm not familiar with dbus and the Python wrappers, but I assume a quickfix could be to increase the timeout of the blocking dbus call to a huge number (15 minutes). Or switch to async APIs, but that would require more changes.
