### ISSUE TITLE
Suse Tumbleweed 32 bit error

### ISSUE THREAD

**Issue by intraxit** [ricardomv/snapper-gui#49]
fol error on suse tumbleweed 32 bit:
snapper-gui
Traceback (most recent call last):
  File "/usr/local/bin/snapper-gui", line 11, in <module>
    load_entry_point('snappergui==0.1', 'gui_scripts', 'snapper-gui')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/snappergui/__init__.py", line 5, in <module>
    gi.require_version("GtkSource", "3.0")
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 3.0

latest version of gtksourceview lib is installed:
No update candidate for 'libgtksourceview-3_0-1-3.24.11-2.10.i586'. The highest available version is already installed.

Is this because of 32 bit ? Than why ?

**Comment by intraxit** [comment]
Nobody taking any notice here ?
