### ISSUE TITLE
Freezes / Stuck when trying to create new snapshot on Fedora 38

### ISSUE THREAD

**Issue by K0-RR** [ricardomv/snapper-gui#60]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/snappergui/mainWindow.py", line 94, in on_create_snapshot
    newSnapshot = snapper.CreateSingleSnapshot(dialog.config,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: error.unknown_config: org.freedesktop.DBus.Error.Failed
```

Also, the dependencies for Fedora are missing. I had to install `gtksourceview3` to be able to run it.

**Comment by K0-RR** [comment]
Seems similar to https://github.com/ricardomv/snapper-gui/issues/38

**Comment by K0-RR** [comment]
Appears to be caused by missing config - fixed by `sudo snapper create-config /`
