### ISSUE TITLE
node children python TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by Mejituu** [ricardomv/snapper-gui#62]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/snappergui/changesWindow.py", line 145, in on_idle_init_paths_tree
self.add_path_to_tree(str(entry[0]), int(entry[1]), files_tree)
File "/usr/lib/python3/dist-packages/snappergui/changesWindow.py", line 70, in add_path_to_tree
node.children[parts[-1]] = changesWindow.TreeNode(path, None, status, False)
~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

**Comment by Mejituu** [comment]
#63

**Comment by Mejituu** [comment]
@ricardomv Hello, would you like to check it out if you have time?

**Comment by stelcodes** [comment]
Having the same issue and I can't use the diff feature at all.
